### ISSUE TITLE
c32 image support?

### ISSUE THREAD

**Issue by binkers87** [queueRAM/Texture64#2]
Will c32 image support be added at some point?

**Comment by queueRAM** [comment]
I’m not familiar with the c32 format. Is that used on the N64?

**Comment by binkers87** [comment]
Yes I can provide some examples if needed. Where should I send them to?

**Comment by queueRAM** [comment]
If you can just tell me which games use it or point me to some documentation, that should be sufficient. Thanks!

**Comment by binkers87** [comment]
So far I've found them in Custom Robo and Custom Robo V2. They are
compressed though.

**Comment by queueRAM** [comment]
Ah, gotcha. Yeah, I had no intent of supporting any of the compression formats. There are better tools to handle the these compressed types and there are just too many to support (MIO0, Yay, Yaz, LZSS, gz, and a ton of other custom formats). It is also more complicated to recompress textures for inserting back into ROM because either the resulting size must be less than or equal to the original and/or tables need to updated with the new location and sizes and those tables are another custom feature.

That said, I'm not opposed to PRs for supporting compression formats.

**Comment by binkers87** [comment]
do you have an email I can reach you at instead? I have a few more
questions about the program.

**Comment by queueRAM** [comment]
Sure, you can find my email address in the git commits

**Comment by queueRAM** [comment]
Closing since I have no plans to support compressed formats. PRs welcome though!
